[package]
name = "svd"
version = "0.1.0"
authors = ["zahar.kravtsov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xmltree = "0.8.0"